---
- name: install PostgreSQL
  hosts: app
  become: yes
  
  tasks:
  - name: Install packages
    ansible.builtin.dnf:
      name:
        - postgresql-contrib
        - '@postgresql:{{ postgresql_vervion }}'
      state: present

  - name: Check if PostgreSQL is initialized
    ansible.builtin.stat:
      path: "{{ postgresql_data_dir }}/pg_hba.conf"
    register: postgres_data

  - name: create data dir and dir for config
    ansible.builtin.file:
      path: "{{ item }}"
      owner: postgres
      group: postgres
      state: directory
      mode: 0700
    with_items:
      - "{{ postgresql_data_dir }}"
      - /etc/systemd/system/postgresql.service.d

  - name: Template a config file to pgdata
    ansible.builtin.template:
      src: ./override.j2
      dest: /etc/systemd/system/postgresql.service.d/override.conf
      owner: postgres
      group: postgres

  - name: Reload systemd
    shell: systemctl daemon-reload

  - name: Initialize the PostgreSQL data directory
    shell: postgresql-setup initdb
