---
- name: install postgress sql
  hosts: app
  become: yes
  
  tasks:
  - name: "Update Repository cache"
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true

  - name: Install packages
    ansible.builtin.apt:
      name: postgresql-{{ postgresql_vervion }},postgresql-contrib-{{ postgresql_vervion }},libpq-dev,python3-psycopg2
      state: present

  - name: Check if PostgreSQL is initialized
    ansible.builtin.stat:
      path: "{{ postgresql_data_dir }}/pg_hba.conf"
    register: postgres_data

  - name: Stop service postgresql
    ansible.builtin.service:
      name: postgresql
      state: stopped
    when: not postgres_data.stat.exists

  - name: Move data directory
    ansible.builtin.lineinfile:
      path: /etc/postgresql/{{ postgresql_vervion }}/main/postgresql.conf
      state: present
      regexp: '(data_directory = )'
      line: \1'{{ postgresql_data_dir }}'
      backrefs: yes
    when: not postgres_data.stat.exists
    notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
