---
- name: install postgress sql
  hosts: app
  become: yes
  
  tasks:
  - name: Install a modularity appstream with de
    ansible.builtin.dnf:
      name:
        - '@postgresql:{{ postgresql_vervion }}'
        - postgresql-contrib
      state: present

  - name: Check if PostgreSQL is initialized
    ansible.builtin.stat:
      path: "{{ postgresql_data_dir }}/pg_hba.conf"
    register: postgres_data

  - name: create data dir
    ansible.builtin.file:
      path:
        - "{{ postgresql_data_dir }}"
      owner: postgres
      group: postgres
      state: directory

  - name: create data dir
    ansible.builtin.file:
      path: /etc/systemd/system/postgresql.service.d
      owner: postgres
      group: postgres
      state: directory

  - name: Template a file to /etc/file.conf
    ansible.builtin.template:
      src: ./override.j2
      dest: /etc/systemd/system/postgresql.service.d/override.conf
      owner: postgres
      group: postgres

  - name: Reload
    shell: systemctl daemon-reload

  - name: ini
    shell: postgresql-setup initdb
