---
- name: install postgress sql
  hosts: app
  become: yes
  
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: postgresql,postgresql-contrib,libpq-dev,python3-psycopg2
      state: present

  - name: Check if PostgreSQL is initialized
    ansible.builtin.stat:
      path: "{{ postgresql_data_dir }}/pg_hba.conf"
    register: postgres_data

  - name: Empty data dir
    ansible.builtin.file:
      path: "{{ postgresql_data_dir }}"
      state: absent
    when: not postgres_data.stat.exists

  - name: Initialize PostgreSQL
    become_user: postgres
    become: yes
    ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
    when: not postgres_data.stat.exists

  - name: Start and enable service
    ansible.builtin.service:
      name: postgresql
      state: started
      enabled: true
